services:
  mh_web:
    build:
      context: .
    container_name: mh_web
    restart: always
    ports:
      - 8000:8000
    # depends_on:
    #   - ngrok
    volumes:
      - .:/app
      - sqlite_db:/data/DB.db
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.mh_web_https.redirectscheme.scheme=https
      - traefik.http.routers.mh_web.entrypoints=web
      - traefik.http.routers.mh_web.middlewares=mh_web_https@docker
      - traefik.http.routers.mh_web.rule=Host(`mh-web.server_name.youdomain`)
      - traefik.http.routers.mh_web_https.entrypoints=websecure
      - traefik.http.routers.mh_web_https.rule=Host(`mh-web.server_name.youdomain`)
      - traefik.http.routers.mh_web_https.tls=true
      - traefik.http.routers.mh_web_https.tls.certresolver=le

  # ngrok:
  #   image: ngrok/ngrok:latest
  #   restart: unless-stopped
  #   command:
  #     - "start"
  #     - "--all"
  #     - "--config"
  #     - "/etc/ngrok.yaml"
  #   volumes:
  #     - ./ngrok.yaml:/etc/ngrok.yaml

  mh_web_redis:
    image: redis:latest
    container_name: mh_web_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - mh_web_redis_data:/data
      - ./redis_conf/users.acl:/usr/local/etc/redis/users.acl
      - ./redis_conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--aclfile", "/usr/local/etc/redis/users.acl"]

    labels:
      - traefik.enable=true
      - traefik.http.middlewares.mh_web_redis_https.redirectscheme.scheme=https
      - traefik.http.routers.mh_web_redis.entrypoints=web
      - traefik.http.routers.mh_web_redis.middlewares=mh_web_redis_https@docker
      - traefik.http.routers.mh_web_redis.rule=Host(`mh-web-redis.server_name.youdomain`)
      - traefik.http.routers.mh_web_redis_https.entrypoints=websecure
      - traefik.http.routers.mh_web_redis_https.rule=Host(`mh-web-redis.server_name.youdomain`)
      - traefik.http.routers.mh_web_redis_https.tls=true
      - traefik.http.routers.mh_web_redis_https.tls.certresolver=le


volumes:
  sqlite_db:
  mh_web_redis_data:
networks:
  default:
    external:
      name: traefik_default