services:
  app:
    build:
      context: .
    container_name: app_web
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - sqlite_db:/data/DB.db
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  sqlite_db: