services:
  app:
    build:
      context: .
    container_name: web
    env_file:
      - .env-doc
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  data:
