services:
  mh_web:
    build:
      context: .
    container_name: mh_web
    ports:
      - 8000:8000
    # depends_on:
    #   - ngrok
    volumes:
      - .:/app
      - sqlite_db:/data/DB.db
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.mh_web_https.redirectscheme.scheme=https
      - traefik.http.routers.mh_web.entrypoints=web
      - traefik.http.routers.mh_web.middlewares=mh_web_https@docker
      - traefik.http.routers.mh_web.rule=Host(`mh-web.server_name.youdomain`)
      - traefik.http.routers.mh_web_https.entrypoints=websecure
      - traefik.http.routers.mh_web_https.rule=Host(`mh-web.server_name.youdomain`)
      - traefik.http.routers.mh_web_https.tls=true
      - traefik.http.routers.mh_web_https.tls.certresolver=le
  # ngrok:
  #   image: ngrok/ngrok:latest
  #   restart: unless-stopped
  #   command:
  #     - "start"
  #     - "--all"
  #     - "--config"
  #     - "/etc/ngrok.yaml"
  #   volumes:
  #     - ./ngrok.yaml:/etc/ngrok.yaml


volumes:
  sqlite_db:
networks:
  default:
    external:
      name: traefik_default